<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;
use Vitis\RestDB\OpenApi\IsOpenApiResource;

/**
 * Generated by restdb:make-openapi-models from petstore.json. This is committed
 * code — edit freely; re-running the command will not overwrite it without
 * --force.
 *
 * @property string|null $id
 * @property int|null $petId
 * @property int|null $quantity
 * @property Carbon|null $shipDate
 * @property string|null $status
 * @property bool|null $complete
 */
class Order extends Model
{
    use IsOpenApiResource;

    protected $connection = 'petstore';

    protected $table = 'order';

    protected $guarded = [];

    public $timestamps = false;

    protected $casts = [
        'petId' => 'integer',
        'quantity' => 'integer',
        'shipDate' => 'datetime',
        'complete' => 'boolean',
    ];
}
