<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Vitis\RestDB\OpenApi\IsOpenApiResource;

/**
 * Generated by restdb:make-openapi-models from petstore.json. This is committed
 * code — edit freely; re-running the command will not overwrite it without
 * --force.
 *
 * @property string|null $id
 * @property string|null $name
 * @property array|null $category
 * @property array|null $photoUrls
 * @property array|null $tags
 * @property string|null $status
 */
class Pet extends Model
{
    use IsOpenApiResource;

    protected $connection = 'petstore';

    protected $table = 'pet';

    protected $guarded = [];

    public $timestamps = false;
}
