<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Vitis\RestDB\OpenApi\IsOpenApiResource;

/**
 * Generated by restdb:make-openapi-models from petstore.json. This is committed
 * code — edit freely; re-running the command will not overwrite it without
 * --force.
 *
 * @property string|null $id
 * @property string|null $username
 * @property string|null $firstName
 * @property string|null $lastName
 * @property string|null $email
 * @property string|null $password
 * @property string|null $phone
 * @property int|null $userStatus
 */
class User extends Model
{
    use IsOpenApiResource;

    protected $connection = 'petstore';

    protected $table = 'user';

    protected $guarded = [];

    public $timestamps = false;

    protected $casts = [
        'userStatus' => 'integer',
    ];
}
